# Generated by Django 5.0.1 on 2024-01-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('division_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('bn_name', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=20)),
                ('long', models.CharField(max_length=20)),
            ],
        ),
    ]
